### ISSUE TITLE
python setup.py egg_info did not run successfully

### ISSUE THREAD

**Issue by pavel4n** [DivineUX23/Audio-to-Audio-translation#2]
I am getting this error during installation. 

pip install -r requirements.txt
Collecting Flask==2.2.3
  Using cached Flask-2.2.3-py3-none-any.whl (101 kB)
Collecting Flask-Bootstrap==3.3.7.1
  Using cached Flask-Bootstrap-3.3.7.1.tar.gz (456 kB)
  Preparing metadata (setup.py) ... done
Collecting Flask-SocketIO==5.3.2
  Using cached Flask_SocketIO-5.3.2-py3-none-any.whl (17 kB)
Collecting Jinja2==3.1.2
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting moviepy==1.0.3
  Using cached moviepy-1.0.3.tar.gz (388 kB)
  Preparing metadata (setup.py) ... done
Collecting ngrok==0.1.6
  Using cached ngrok-0.1.6.tar.gz (3.5 kB)
  Preparing metadata (setup.py) ... done
Collecting nltk==3.8.1
  Using cached nltk-3.8.1-py3-none-any.whl (1.5 MB)
Collecting openai==0.27.1
  Using cached openai-0.27.1.tar.gz (57 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pytube==12.1.2
  Downloading pytube-12.1.2-py3-none-any.whl (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.0/57.0 KB 2.4 MB/s eta 0:00:00
Collecting requests==2.28.2
  Downloading requests-2.28.2-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 KB 7.6 MB/s eta 0:00:00
Collecting click>=8.0
  Downloading click-8.1.7-py3-none-any.whl (97 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.9/97.9 KB 11.6 MB/s eta 0:00:00
Collecting Werkzeug>=2.2.2
  Downloading werkzeug-3.0.3-py3-none-any.whl (227 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 227.3/227.3 KB 10.3 MB/s eta 0:00:00
Collecting itsdangerous>=2.0
  Downloading itsdangerous-2.2.0-py3-none-any.whl (16 kB)
Collecting dominate
  Downloading dominate-2.9.1-py2.py3-none-any.whl (29 kB)
Collecting visitor
  Downloading visitor-0.1.3.tar.gz (3.3 kB)
  Preparing metadata (setup.py) ... done
Collecting python-socketio>=5.0.2
  Downloading python_socketio-5.11.2-py3-none-any.whl (75 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 75.7/75.7 KB 12.8 MB/s eta 0:00:00
Collecting MarkupSafe>=2.0
  Downloading MarkupSafe-2.1.5-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (26 kB)
Collecting decorator<5.0,>=4.0.2
  Downloading decorator-4.4.2-py2.py3-none-any.whl (9.2 kB)
Collecting proglog<=1.0.0
  Downloading proglog-0.1.10-py3-none-any.whl (6.1 kB)
Collecting tqdm<5.0,>=4.11.2
  Downloading tqdm-4.66.4-py3-none-any.whl (78 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.3/78.3 KB 10.1 MB/s eta 0:00:00
Collecting numpy>=1.17.3
  Downloading numpy-1.26.4-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (14.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.2/14.2 MB 11.1 MB/s eta 0:00:00
Collecting imageio<3.0,>=2.5
  Downloading imageio-2.34.1-py3-none-any.whl (313 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 313.5/313.5 KB 11.6 MB/s eta 0:00:00
Collecting imageio_ffmpeg>=0.2.0
  Downloading imageio_ffmpeg-0.5.1-py3-none-manylinux2014_aarch64.whl (22.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 22.9/22.9 MB 9.9 MB/s eta 0:00:00
Collecting ping
  Downloading ping-0.2.tar.gz (10 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-ddfzrl2n/ping_3f42c076baab46148a2925351d118301/setup.py", line 23, in <module>
          from ping import __version__
        File "/tmp/pip-install-ddfzrl2n/ping_3f42c076baab46148a2925351d118301/ping.py", line 196
          except socket.error, (errno, msg):
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
      SyntaxError: multiple exception types must be parenthesized
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by DivineUX23** [comment]
try installing a newer version of "ping", maybe "ping3"
